sonar.projectKey=leapmentor-frontend
sonar.projectName=LeapMentor Frontend
sonar.host.url=http://localhost:9000
sonar.token=sqp_ec38636a6c3d68490d155543b2009808dac5d6fe
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx,**/src/test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info